### ISSUE TITLE
UX flow

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#100]
# Problem
1. First-time user can not see Register link and it's not clear how to proceed
1. There is no link to Register on Dashboard

# Proposed solution
1. Put register link on home page (But if not logged in, then still direct to auth workflow)
2. Put Register link / 'Box' onto Dashboard so it's clear

**Comment by gubuntu** [comment]
I unticked the 'login required' checkbox on the Register page so now anyone can see the Register link. But that's just a temporary fix because the link is already out there and people are trying to register. 

We still need to make all the links very clear on the home page AND the dashboard AND link registration (i.e. purchase of conference attendance 'products') to a user account.

**Comment by cchristelis** [comment]
We need to redirect users without an account to login/register before being able to submit papers and buy courses.

**Comment by euclidian** [comment]
I think this is a duplicate with #107
