### ISSUE TITLE
fix post-registration url

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#102]
from Jeff:

> when I went to "My Dashboard" and then created a profile account, after creating a user account I was sent https://qgis.org.za/en/ and I could not find a link back to https://foss4g-africa.org/ (that will be very confusing to users who register)

**Comment by euclidian** [comment]
duplicates in #91

**Comment by cchristelis** [comment]
# Proposed Solution

Update redirect

**Comment by euclidian** [comment]
I can't reproduce this. 

I did this procedure
- Signup as a new user
- Get to dashboard
- Create a speaker profile
- Save speaker profile

I was ended up on https://foss4g-africa.org/en/dashboard/

**Comment by euclidian** [comment]
can we close this @gubuntu
