### ISSUE TITLE
Improve Registration UX

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#107]
feedback from a user:
>This is a bit messy once you "buy". Still confusing that this is registration?

![Uploading WhatsApp Image 2017-03-29 at 12.20.27.jpeg…]()

Let's make this more intuitive. Suggestions:
- replace 'Buy' with 'Register / Book'
- guide the user to add all their required items to the 'cart' before 'checking out' (replace 'Checkout' with 'Generate invoice')
- Add fields to the user information form (either on signup or purchase of a conference registration) 
  - shirt size
  - dietary preferences
  - Institution/school
  - SAGTA member y/n
  - (teachers) GIS experience scale 1-5
  - Billing details of employer or other party if not the same as yours (maybe we use the existing 'billing' and 'shipping' details and make it clear that if an employer is paying, their details must go into the billing section and the user's details must go into the shipping section.
- any other ideas?

**Comment by cchristelis** [comment]
# Proposed Solution

[ ] - Update button text
[ ] - @gubuntu could you specify text to use to advise users to add all items.
[ ] - Please add extra items.
