### ISSUE TITLE
Typo on blog page

### ISSUE THREAD

**Issue by sokolic** [kartoza/qgis.org.za#11]
There is a typo in the DISQUS section at the bottom of the blog page. The placeholder text for the website input has **webiste** instead of website. Have a look at [https://qgis.org.za/en/blog/first-ever-qgis-cape-town-meetup/](url)

**Comment by timlinux** [comment]
Also we should set up a disqus profile for this site rather than using the kartoza one which is currently there by default....

**Comment by gubuntu** [comment]
duplicate of #6
