### ISSUE TITLE
user can't reset password

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#112]
From Serena Coetzee

>I reset my password for the username ‘serena’, but still cannot login….this is the error message I get: 'The username and/or password you specified are not correct.’

Do Symposion accounts use Django auth and the Django user framework? i.e. is a Symposion 'account' the same as a Django 'user'?

**Comment by gubuntu** [comment]
@euclidian besides the PR link to closing an issue (and this is a general comment), please put a comment in the Issue thread (here) with a brief explanation of what the problem was and what you did to fix it, as well as some sort of evidence that it is working (a screenshot or copy and paste of an email or page)

**Comment by euclidian** [comment]
Sorry, forgot to do that.

The problem is the reset url that listed in the email was wrong. It was pointing to qgis site, when it should went to foss4g africa. 

This is email example for that:

```
You're receiving this e-mail because you or someone else has requested a password for your user account.
It can be safely ignored if you did not request a password reset. Click the link below to reset your password.


https://foss4g-africa.org/en/accounts/password/reset/key/c-4l5-d319139e091b552d/
```

**Comment by gubuntu** [comment]
Ah, OK, LGTM thanks
