### ISSUE TITLE
Change 'Save for Later' in Shop

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#116]
Rather say 'Add to Cart'

**Comment by gubuntu** [comment]
looking at the code, it seems like there is 'wishlist' functionality and that 'Buy' already means 'add to cart'. We want an intuitive interface here for people to order conference items. Please ensrue the workflows work and make sense to a non-technical user. 

So, I think the code's 'add_to_cart' should be 'Order' to the user. 

And if the 'wishlist' functionality does indeed work, then call it 'Add to wishlist'. 

To confirm that these both work, the user must be able to logout and then log back in and see their unprocessed order and their wishlist. 

And the user must be able to add wishlist items to their cart (i.e. order them)

I'm sure you are familiar with some good e-commerce sites - our experience needs to also be a good e-commerce experience. Many big sites use Cartridge (see list at https://www.diycode.cc/projects/stephenmcd/cartridge) so let's make ours just as slick an experience.

**Comment by euclidian** [comment]
WIshlist is working 

Here is screenshot of wishlist page. The url is `/shop/wishlist` maybe we can add it to top navigation bar from mezzanine

![image](https://cloud.githubusercontent.com/assets/2271663/24943334/64fa9320-1f80-11e7-94b4-87cc249d55a1.png)

**Comment by gubuntu** [comment]
OK - yes please go through the whole shop interaction in the shoes of a user and check that you can actually get to all the functionality and that it all works

**Comment by euclidian** [comment]
Fixed in #143
