### ISSUE TITLE
make accommodation ordering more intuitive

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#122]
This might be a Cartridge enhancement:

I've treated accommodation as a regular Product. so if you want to book multiple nights you have to choose each night as a separate instance of a Product and add each to your cart. 

I think the simplest way to fix this would be to add each instance to the page with tickboxes instead of putting them in a dropdown.

Same goes for single day registrations.

In fact this ticket just extends #96: Put all Products AND all their instances nicely arranged on one page to make it easy to order exactly what you want in one step.

**Comment by cchristelis** [comment]
# Proposed Solution

Add variants.

**Comment by gubuntu** [comment]
added two 3-night variants
