### ISSUE TITLE
User can't easily get back to their Cart from anywhere in the website

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#123]
make it easy...

**Comment by euclidian** [comment]
Please suggest me on UI/UX about this. I'm not really good at this. Should I just add label on top navigation bar?

**Comment by gubuntu** [comment]
Well we seem to have two design patterns in the site - Mezzanine and Pinax/Symposion so I imagine you should try to fit in with one of them. For now, do your best, we need something to work. @dimasciput has good design ideas and skills to help.

**Comment by cchristelis** [comment]
# Proposed Solution

Make this a menu item.
