### ISSUE TITLE
please figure out schedule builder

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#130]
I have spent ages trying to get the schedule builder (https://symposion.readthedocs.io/en/latest/schedule.html) to work but I keep getting an error. I'm not sure if I've missed setting something up in admin, or if something's missing or wrong in the csv file or if it's a bug or misconfiguration in the system.

I can get the form up at /schedule/sagta-general-track/edit/ (there is a form url for every schedule you create) but keep getting en error on submission of the csv. 

Please get it working (in staging) with https://github.com/kartoza/qgis.org.za/blob/develop/django_project/conference_schedules/FOSS4GAfrica_schedule.csv asap.

**Comment by gubuntu** [comment]
I still cannot get this to work on staging or production and it is absolutely critical that we can set up the conference schedule properly. Please get it to work with clear notes about any tips and tricks, such as what needs to be set up beforehand (just sections like https://foss4g-africa.org/en/admin/symposion_conference/section/6/ to enable the example in the OP)

**Comment by euclidian** [comment]
Maybe you are using wrong formatted csv. I've tested in on production and it is working

Notes on CSV :
- Make sure  csv file uses the right quote mark
- Make sure hour format is HH:MM with 24 hours format

Example on working csv

[example.csv.zip](https://github.com/kartoza/qgis.org.za/files/956786/a.csv.zip)

This is actually a csv file, but github prevent me from uploading a .csv file so I added .zip extension. Just rename it after you download it

**Comment by gubuntu** [comment]
@euclidian pls see https://github.com/kartoza/qgis.org.za/pull/148 and get it working in production, I'm pulling my hair out trying with no success and non-informative error message.

**Comment by euclidian** [comment]
can I close this @gubuntu ?

**Comment by gubuntu** [comment]
Yes ok
