### ISSUE TITLE
Fix Schedule Layout

### ISSUE THREAD

**Issue by euclidian** [kartoza/qgis.org.za#133]
![image](https://cloud.githubusercontent.com/assets/2271663/25158428/8bfa91f8-24d2-11e7-9c32-4ed5476de35e.png)

**Comment by gubuntu** [comment]
what has actually been fixed?

**Comment by euclidian** [comment]
This is about schedule's table layout that went havoc after we upload a new csv file. You can see on picture above where table's header is not appropriately aligned with its content.

**Comment by gubuntu** [comment]
OK. Was there a bug in symposion, I'm wondering why it didn't work properly out the box. Or are we not following the right workflow...? (hope you get better soon @euclidian )

**Comment by euclidian** [comment]
I think this is a bug on symposion
