### ISSUE TITLE
sponsor logo and description fields not editable via admin

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#140]
https://foss4g-africa.org/en/admin/symposion_sponsorship/sponsor/

Please fix

**Comment by dimasciput** [comment]
@gubuntu you can add web logo or print logo through sponsor benefits
![screen shot 2017-04-28 at 9 35 39 am](https://cloud.githubusercontent.com/assets/1979569/25512248/69d19cd6-2bf6-11e7-85fc-f89234d28c49.png)

**Comment by gubuntu** [comment]
@dimasciput / @euclidian Kartoza had a logo in sponsor benefits and I uploaded a replacement but the sponsor admin page and user Dashboard  / website do not show it anywhere.

**Comment by gubuntu** [comment]
also, does it have to be a specific size or does Symposion resize it?

**Comment by ann26** [comment]
@gubuntu @cchristelis  this issue is solved in #152
