### ISSUE TITLE
add domain to nginx config

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#15]
Please urgently add these domains to the config, to the same vhost as the qgis.org.za domain. They will be distinguished by Django Sites:

- foss4g-africa.org
- www.foss4g-africa.org

**Comment by gubuntu** [comment]
@dimasciput please do this, we really need this working

**Comment by dimasciput** [comment]
@gubuntu done, I updated the server. And here's the PR : https://github.com/kartoza/qgis.org.za/pull/16

**Comment by gubuntu** [comment]
@dimasciput please fix and deploy again from latest develop, these config changes have been lost. Not sure if it was from @sokolic 's recent activity?

**Comment by dimasciput** [comment]
What's wrong? I still can open the sites.

**Comment by gubuntu** [comment]
- I think browser caches are getting in the way if I switch between sites I'm getting lots of page not found errors on both sites. 
- The foss4g-africa.org site is not redirecting to the 2017 page like it was last week. 
- I deleted www.foss4g-africa.org site from Django sites since it treats it as a separate site (it seems to have added it automatically - I just want foss4g-africa.org). Nginx must still accept www.foss4g-africa.org but maybe needs to rewrite it to remove the www?

**Comment by dimasciput** [comment]
@gubuntu I have redirected www.foss4g-africa.org to foss4g-africa.org

**Comment by gubuntu** [comment]
working nicely, thanks
