### ISSUE TITLE
fix menu bar

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#155]
the menu bar is too big and pushes over the top page header - rather implement as a drop down menu or a side index of find a few short words for the menu

**Comment by euclidian** [comment]
I found out how to create a dropdown menu. It is already there on mezzanine, but not really intuitive

![18339473_10209271358047112_1281468692_o](https://cloud.githubusercontent.com/assets/2271663/25692139/8caa9982-30ca-11e7-9eae-7a7523544198.gif)

**Comment by gubuntu** [comment]
thanks @euclidian, that's great to know. That fixes #132, not #155

**Comment by euclidian** [comment]
fixed in #170
