### ISSUE TITLE
Accepted domains list

### ISSUE THREAD

**Issue by timlinux** [kartoza/qgis.org.za#2]
Please make sure our nginx confess accept requests for these domains:

* qgis.org.za
* www.qgis.org.za

**Comment by gubuntu** [comment]
@dimasciput please deploy asap so the site can go live and create accounts for 
- tim
- gavin
- christian
- frank (frank@gis-solutions.co.za)
- immo (immo@blecher.co.za)

**Comment by gubuntu** [comment]
@dimasciput please complete

**Comment by dimasciput** [comment]
@gubuntu I have created tim and christian for superuser, the password is the same with the username. The others have already been added. Will close this issue.
