### ISSUE TITLE
foss4g-africa.org: dockerise PinaxCon

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#21]
# Problem

We need a functional website for FOSS4G Africa 2017 during this week.

We are going to try to use the same system that http://2016.foss4g.org used,

# Proposed solution

- Fork https://github.com/vmx/pinaxcon (into /kartoza if you can, else into your own account to start with)
- dockerise it 
 - try it out conventionally first if you struggle to orchestrate it with docker-compose

**Comment by gubuntu** [comment]
@euclidian please report progress

Then, please make a call with input from @cchristelis about how to proceed. The urgency is to have a functional conference site THIS WEEK so we can't afford to spend ages experimenting.

However, we want to add the conference functionality to our docker-mezzanine core app as a bunch of pluggable components (e.g. as Django apps) and not necessarily bring in another big dependency, which Pinax might be. On the other hand there might be no harm and even benefit in adding symposion to mezzanine. 

So, I think we should actually focus now on bringing symposion and elements from Volker's repo into docker-mezzanine rather than trying to deploy and modify Volker's full project.

**Comment by euclidian** [comment]
It's already been dockerized in PR https://github.com/kartoza/PinaxCon/pull/1
It is just a simple dockerized system, not using kartoza standard. But it is working. I'm working on #25 but i'm really still experimenting. Will consult @cchristelis for best way to counter this

**Comment by euclidian** [comment]
fixed in branch pinaxcon. Using mezzaine as code base and integrated with symposion

please review @cchristelis @gubuntu
