### ISSUE TITLE
foss4g-africa.org: integrate pinaxcon with mezzanine

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#22]
If it's possible and makes sense, we need  pinaxcon to run as an app or project with our docker-mezzanine project and then specifically with this instance, qgis.org.za.

# proposed solution
Try this

**Comment by euclidian** [comment]
fixed in branch pinaxcon

**Comment by gubuntu** [comment]
@euclidian please close if fixed
