### ISSUE TITLE
foss4g-africa.org: deploy to staging

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#23]
we need staging.foss4g-africa.org by Weds 15 Feb

# solution
deploy to a staging VPS. Ask Gavin or @christelis at the time to
- set up cloudflare DNS
- allocate a host

**Comment by gubuntu** [comment]
host: 78.47.48.42 ssh port 22 as root. Send me your pubkey if you can't get in.

It's a small Kartoza Hetzner VPS running docker engine. 

Gerald Fenoy is setting up the DNS for staging.foss4g-africa.org but in the meantime we can just use the ip and /etc/hosts.

**Comment by euclidian** [comment]
fixed in new branch pinaxcon

**Comment by gubuntu** [comment]
close it when nginx is set up to accept staging.foss4g-africa.org

**Comment by euclidian** [comment]
http://staging.foss4g-africa.org:6045/dashboard
