### ISSUE TITLE
foss4g-africa.org has links and content from qgis.org.za

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#26]
# Problem

http://foss4g-africa.org.za has a redundant Home page link as well as boilerplate (header and footer) carried over from qgis.org.za

# Solution

Surely Django Sites should result in apparently completely independent sites? 
- remove the redundant home link
- change the boilerplate for the foss4g site (unless it keep the host site boilerplate by design)

**Comment by dimasciput** [comment]
Addressed in https://github.com/kartoza/qgis.org.za/pull/47
