### ISSUE TITLE
foss4g-africa.org: Incorrect URL for qgis.org.za

### ISSUE THREAD

**Issue by sokolic** [kartoza/qgis.org.za#27]
On the FOSS4G Afica 2017 home page there are logos for OSGEO, QGIS.ORG.ZA, SAGTA and Geo for All. The URL linked to the QGIS.ORG.ZA logo is incorrect and should be changed to [https://qgis.org.za/en/](url)

**Comment by gubuntu** [comment]
H @sokolic you can fix this! qgis.org.za and foss4g-africa.org are running on the same Django instance using Django sites, so just use your admin login. 

Also, the url should be https://qgis.org.za (leave out the /en)

**Comment by sokolic** [comment]
Done. That was easy with Mezzanine!
