### ISSUE TITLE
we need registration functionality

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#28]
Attendees need to register for the conference by choosing from one or more categories

**Comment by gubuntu** [comment]
The registration categories should map to items in a Cartridge shop
- add Cartridge to the project as we have in kartoza/docker-mezzanine. 
- one way to work this could be to define the categories (product instances) in Cartridge and then show them as available items for registration on the conference registration page
- the payment can proceed via whatever method is set up in Cartridge (defaulting to the manual method we have in the kartoza website)

Examples are
- SAGTA / GeoforAll subconference 26-28 June R___
- FOSS4G / QGIS subconference 28-30 June R___
- pre-conference tour 25 June R___
- dinner 26 June R___
- dinner 27 June R___
- code sprint 1 July R0 (free)
- SASDI workshop 27 June R0 (free)
- all five days R___
- daily rate (one for each day) R___
Discount codes
- teacher
- SAGTA member
- student

**Comment by gubuntu** [comment]
The sign up functionality is working - that's the first step to registering. I think the registration options should apear on user's dashboard along with submitting a paper etc.

**Comment by gubuntu** [comment]
@euclidian please split this into at least two issues. The signup part you can close but please keep the rest of the registration items open. They're not a blocker for first release

**Comment by euclidian** [comment]
Move registration items into #38
