### ISSUE TITLE
qgis.org.za: make home page editable

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#32]
# Problem
The home page appears to be static and is not what appears in https://qgis.org.za/en/admin/pages/richtextpage/2/. Well, the images are but the text isn't. 

# Solution
Make home page text editable through admin. 

At the same time, add a link to sign up to the mailing list to the Orange area: https://lists.osgeo.org/mailman/listinfo/qgis-za-user

**Comment by sokolic** [comment]
Details of the mailing list and the link were added to the static index page 12 days ago. These changes still need to be deployed.

**Comment by dimasciput** [comment]
Hi @gubuntu , which home page section should editable?

**Comment by gubuntu** [comment]
Just like in Kartoza website, the whole home page.

**Comment by dimasciput** [comment]
I made the description in orange section is editable in admin page :

![screenshot from 2017-02-22 20 38 41](https://cloud.githubusercontent.com/assets/1979569/23213872/47cf48d4-f93f-11e6-835c-ce8d8c0ee8f6.png)
![screenshot from 2017-02-22 20 38 53](https://cloud.githubusercontent.com/assets/1979569/23213878/488ba966-f93f-11e6-9c73-af7e0b2a81a1.png)

And I have updated the server, I will close this issue
