### ISSUE TITLE
foss4g-africa.org: first production release

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#36]
1. qgis.org.za is currently in production with foss4g-africa.org in production as a Django site. 
1. IF we are sure that the new conference site with merge nicely with the existing site as a Django site then let's do that
 1. merge and release at qgis.org.za
1. ELSE we keep it separate and deploy to production on a new server
 1. in which case tag a release off the pinaxcon branch and deploy on a dedicated server. 

Dependencies: #30 #35

**Comment by euclidian** [comment]
Addressed in #52
