### ISSUE TITLE
Foss4g not correct in production

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#52]
@euclidian I still see the old home page with dual Home links, not the new one with register option

Please fix

**Comment by euclidian** [comment]
@gubuntu it seems my public key is not yet set in production. Who should I contact for this?

**Comment by gubuntu** [comment]
I know @dimasciput and @timlinux have access, hopefully one of them can add your (and my) pubkey. Otherwise I might have to go in via Hetzner rescue mode but I'd rather not.

**Comment by euclidian** [comment]
I already have @dimasciput set things up for me. I can access it now. Will deploy it now

**Comment by euclidian** [comment]
deployed
