### ISSUE TITLE
release papercuts

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#54]
@euclidian please fix these issue today if you can, either through admin or a hotfix release as appropriate:

## qgis.org.za

- [x] remove Dashboard from qgis.org.za

## foss4g-africa.org

- [x] let us know how to edit the template / home page. I would like to update footer details for foss4f without affecting qgis.org.za
- [x] change Bonn FOSS4G 2016 logo and any other references through the site to FOSS4G Africa 2017 logo and wording
- [x] fix Django sites. There should be two sites: qgis.org.za (how can this be missing and still work?) and foss4g-africa.org. Remove or change references to or explain proposals.2016.foss4g.org????
- [x] where do I edit the login / dashboard page content? e.g. I need to change 'Sign up here to submit a workshop or a talk for the general session of the FOSS4G 2017 conference.'  to 'Sign up here to register or to submit a workshop or a talk for the SAGTA /  FOSS4G Africa 2017 conference.' and remove the link (which goes to the Boston FOSS4G in August) 

I still have to familiarise myself with Symposion so I'm sure I'll find more...

**Comment by euclidian** [comment]
- Template home page can be edited directly in admin page. Make sure that meta variable in editore match foss4g url site
- Footer page for now still hardcoded in html
- Mezzanine actually can't handle multiple home page for a different site in one django deployment. Unless we separate its deployment with same code base but with a different SITE_ID variable. So I add function to read metadata for home page to match its url page. So any page that don't have metadata matches its url will go to qgis.org.za
- Login / Dashboard page still hardcoded in html

**Comment by euclidian** [comment]
I'll move "remove dashboard from qgis.org.za" to separate issue. Because it needs to be extended from Mezzanine's admin page

**Comment by gubuntu** [comment]
OK, thanks for explanations, Please tick off items as you do them or move to their own issues. Fixing branding is NB.

**Comment by euclidian** [comment]
Move "change Bonn FOSS4G 2016 logo" to another issue. It should be using image from media with pre-defined image name

**Comment by euclidian** [comment]
Move wording to another issue
