### ISSUE TITLE
site emails must work

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#58]
confirm PostFix is installed and working
- and that the email verification process works for new accounts

(kartoza/docker-postfix)

**Comment by gubuntu** [comment]
this is critical, no-one can register or upload submissions until this is working

**Comment by euclidian** [comment]
on it, email is working but it seems confirmation page is throwing error
sometimes it goes to spam though. I set sender from no-reply@kartoza.com

**Comment by gubuntu** [comment]
please set sender as secretary@sagta.org.za

**Comment by euclidian** [comment]
Move it to #72
