### ISSUE TITLE
Settings link in Dashboard throws error

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#63]

**Comment by euclidian** [comment]
Which setting does make this error? I just tried it and it works

![image](https://cloud.githubusercontent.com/assets/2271663/23644869/f57cadc2-033b-11e7-9988-bf801c7d3397.png)

**Comment by gubuntu** [comment]
This one

![screenshot from 2017-03-07 08-44-44](https://cloud.githubusercontent.com/assets/496911/23645160/6ac68b6c-0313-11e7-9154-ff11d3aa2ac4.png)

**Comment by euclidian** [comment]
I'm not sure about this issue. I checked on production and it works

![settings](https://cloud.githubusercontent.com/assets/2271663/23689363/92163fd0-03ec-11e7-852d-dbd82cee9610.gif)

**Comment by gubuntu** [comment]
I'm afraid I still get an error in production and staging, please investigate further

**Comment by gubuntu** [comment]
I created a new account on staging through the front-end (not admin) and it works with that account. So either it doesn't work with pre-existing accounts or it only works with non staff/superuser accounts?

**Comment by euclidian** [comment]
Can you provide me with account that cause this error? I'll look it up by dumping production db to my dev

**Comment by gubuntu** [comment]
gavin

**Comment by cchristelis** [comment]
@gubuntu, since this does not affect any new users, let's ask the handful​ of users that are affected to just re-register?

**Comment by euclidian** [comment]
can we close this?  @gubuntu

**Comment by gubuntu** [comment]
no, it's still causing the same error. I signed up as a new user (gubuntu), then clicked on Settings in my dashboard and got the same error.
