### ISSUE TITLE
cannot submit proposal

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#66]
I have created various proposal sections but when I try to submit one, I get an error. 

This is also critical to have working asap. 

I think it might have somthing to do with that proposals.2016.foss4g.org url that's hanging around. 

Get the default local symposion submission working.

**Comment by euclidian** [comment]
Proposal's slug needs to match default symposion's slug which is talk, workshop, and map. 
Each slug has its own templates.
So
- If we need another section but using the same template with existing, it is just a matter of creating new slug with the same template.
- If we need new template then, please create an issue for each template needed

**Comment by euclidian** [comment]
Addressed in #71
