### ISSUE TITLE
Use social auth for login / registration

### ISSUE THREAD

**Issue by timlinux** [kartoza/qgis.org.za#69]
Please dont make me create yet another user account and password. Please use social auth so that we can use github / twitter / fb etc account to log in and register.

![2017-03-07 15_51_21-qgis south africa user group _ log in](https://cloud.githubusercontent.com/assets/178003/23659231/25757268-034e-11e7-8e8b-a4bcb5c8cd0d.png)

**Comment by gubuntu** [comment]
only close when FB and Google are added. Note that all criteria in an Issue must be addressed before closing it. 

you are welcome to add others too. 

Most of the people coming to the conference won't have a GitHub account!

**Comment by euclidian** [comment]
@gubuntu Can I have tokens for Github, Facebook and Google from Kartoza page? For now I'm using tokens from my account

**Comment by gubuntu** [comment]
GitHub auth not working: it links to http://0.0.0.0:63303/en/social/complete/github/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=HBhYwzdaiNJXDFmDSi2cxl4YM0sdsCwZ

**Comment by gubuntu** [comment]
fix github author remove since it's not working

**Comment by euclidian** [comment]
fixed in #164
