### ISSUE TITLE
what are boxes

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#85]
Investigate the intent and use of 'boxes'

https://foss4g-africa.org/en/admin/boxes/box/

Are these part of Symposion or added by Bonn?

**Comment by euclidian** [comment]
It is the editable panel on right side for sponsors. We can add it more and put it on template

**Comment by gubuntu** [comment]
can you do that in staging to confirm that it works?

**Comment by euclidian** [comment]
Adding a box need to be done on html template, butt after that we can edit it right on the spot (logged in as admin)

![image](https://cloud.githubusercontent.com/assets/2271663/24276931/9c982608-106c-11e7-849f-f485f138bc83.png)
