### ISSUE TITLE
Fix shop appearance

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#91]
# Problem

Shop (for registration and accommodation) looks horrible

https://foss4g-africa.org/register/

# Proposed Solution
- [ ] bring 'Register' link (product page) onto Dashboard so it fits Symposion layout
- [x] User must be logged in to register (i.e. to buy products)
- [ ] Make product page or widget same style as rest of conference (not QGIS template) 
- [ ] Fix the appearance of the product options to fit in with the rest of the conference theme. At the minimum fix the layout so you can clearly see all products

**Comment by gubuntu** [comment]
bring in all? Cartridge mods from docker-mezzanine (kartoza.com) - they will fix several layout and UX issues. Try to register for a course under the Training menu in kartoza.com to see the UX.

**Comment by euclidian** [comment]
I already bring it all. But it seems it clashes with symposion css. I'll look into it

**Comment by gubuntu** [comment]
almost there (i hope) - this one is critical to do first thing Weds (if you're not on holiday) else Thurs
